version: '3.8'
services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
      - redis
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    restart: unless-stopped

  y-websocket:
    image: node:18
    container_name: y-websocket
    working_dir: /app
    volumes:
      - ./y-websocket:/app
    command: ["node", "server.js"]
    ports:
      - "1234:1234"
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  mongo_data:

